puppetlabs/puppetlabs-azure

- README.md
- metadata.json
- Project page for this module should be the puppetlabs-azure repo
- README still contained a link to TravisCI at puppetlabs-msazure
> (maint) Fix errant URLS in README / metadata

- lib/puppet/type/azure_vm.rb
- spec/unit/type/azure_vm_spec.rb
Related to Puppet Labs Support Request #16778.  Azure VM (ARM) name length is 64 characters according to GUI.
> Correct name length error check

- README.md
- lib/puppet/feature/azure_hocon.rb
I've tested this with the 0.9.3 version of the hocon gem, but this needs to be tested against either the old 0.9.4 version or the upcoming 1.0.0 version of the gem.
/cc @DavidS @cprice404 @fpringvaldsen for review and merge.
> (FM-4762) Update for Hocon 1.0.0 compatibility.

- Gemfile
Our code is not prepared to work with the changes in 0.2, so this
tightens the dependencies down to the known good versions.
> (MAINT) Specify narrower bounds on required gems

- README.md
- Use appropriate quoting in the README for installing gems on Windows under cmd
> (maint) Update Windows installation

- README.md
That way UTF-8 encoding issues with a BOM are a thing of the past.
> Update README to require a current version of hocon

- spec/acceptance/arm_vm_spec.rb
- spec/acceptance/fixtures/azure_vm.pp.tmpl
Mustash interpolate strings and incorrectly quotes them. This allows non
string values to be added to the manifest templates without HTML
interpolation.
> Fix quote interpolation

- lib/puppet_x/puppetlabs/azure/provider_arm.rb
- spec/spec_helper_acceptance.rb
These caused the calls to be either non-blocking or no not even execute
> Fix incorrect rest calls

- README.md
- lib/puppet/provider/azure_vm/azure_arm.rb
- lib/puppet/type/azure_vm.rb
- lib/puppet_x/puppetlabs/azure/provider_arm.rb
- spec/acceptance/arm_vm_datadisks_spec.rb
- spec/acceptance/fixtures/azure_data_disks.pp.tmpl
This adds data_disks property that expects a hash of hashes. The key
should be the name of the disk and the hash contains up to five
properties that apply to the disk. The subhash is caching,
create_option, data_size_gb, lun, and vhd.
> (MODULES-3614) Add data_disks to azure_vm

- lib/puppet_x/puppetlabs/azure/provider_arm.rb
- spec/acceptance/arm_vm_spec.rb
- spec/spec_helper_acceptance.rb
Previously the test tried to use `@machine.ip` to access the public IP
address of the newly created azure instance, just like the similar test
in `azure_vm_classic`. This doesn't work, so we need new methods to find
the public ip address of the azure ARM instance before the test can pass.
> Fix test of customdata on azure_vm

- README.md
- examples/data_disks.pp
- examples/pe_plan.pp
- lib/puppet_x/puppetlabs/azure/provider_arm.rb
- rakelib/acceptance.rake
- spec/acceptance/arm_vm_datadisks_spec.rb
- spec/acceptance/arm_vm_plan_spec.rb
- spec/acceptance/arm_vm_spec.rb
Using `plan` is incompatible with `image` though one of the two is
required.
Also fixes extension testing (via removing broken dns), avoids
conflicting network interface names during testing, and adds 2016.2
acceptance test rake jobs.
> (FM-5488) Fix plan for azure_vm

- lib/puppet_x/puppetlabs/azure/provider_arm.rb
- spec/spec_helper_acceptance.rb
The old image link had been deprecated by a new release.
> (maint) windows classic server2012r2 vhd update for the acceptance tests

- README.md
This calls out the list of gems required, and their version requirements, so it's hard to miss in the README. Given the error you get if you installer a version of some of these gems that's newer than May 2016 is so [obtuse](https://tickets.puppetlabs.com/browse/MODULES-5477) I think it's important this is called out more visibly in the readme.
> (MODULES-4466) improve visibility of ruby gem versions required

- README.md
(Subject to testing) `azure_vm` can setup Guest diagnostics already by configuring the appropriate data in `extensions`.  Configuring boot diagnostics would require an additional parameter but is probaly best handled through the Azure portal anyway
> (MODULES-5008) Notes on configuring diagnostics 2/6

- Gemfile
- README.md
- lib/puppet/provider/azure_vm/azure_arm.rb
- lib/puppet_x/puppetlabs/azure/provider_arm.rb
Upgrade gems:
* azure_mgmt_compute (0.10.0)
* azure_mgmt_network (0.10.0)
* azure_mgmt_resources (0.10.0)
* azure_mgmt_storage (0.10.0)
To enable support of new azure features such as "managed disks".  `rake spec` passing after code refactor and am able to provision vms using `azure_vm`, however, unable to acceptance test given need to access puppet internal test resources to perform them.  The `data_disks` parameter is not updatable (although it works on create) after applying this patch but I think it may have been broken before this update.
> (MODULES-5036) azure gem upgrades for new features 3/6

- Gemfile
- README.md
- lib/puppet/provider/azure_vm/azure_arm.rb
- lib/puppet/type/azure_vm.rb
- lib/puppet_x/puppetlabs/azure/property/boolean.rb
- lib/puppet_x/puppetlabs/azure/provider_arm.rb
- spec/unit/type/azure_vm_spec.rb
Support azure's managed disks feature with a new parameter, `managed_disks`.  When selected, we will no longer specify VHD options or create a storage account since Azure now does all this for us.  Access to the ruby model classes supporting this feature is required to enable this (https://github.com/puppetlabs/puppetlabs-azure/pull/143)
> (MODULES-5004) Support for "managed disks" 4/6

- Gemfile
- README.md
- lib/puppet/provider/azure_vm/azure_arm.rb
- lib/puppet/type/azure_vm.rb
- lib/puppet_x/puppetlabs/azure/property/boolean.rb
- lib/puppet_x/puppetlabs/azure/provider_arm.rb
- spec/unit/type/azure_vm_spec.rb
Add a new parameter `network_security_group_name` that allows the network security group name to be set at time of VM creation.  If security group already exists, it will be attached to the VM, otherwise it will be created.  If the special name `None` is passed, then no security group will be created or associated.  Due to the way azure API orders resources, its not optimal to inspect the VM and return the security group name that applies (security groups belong to network interfaces not VMs), so the `puppet resource` command does not interrogate the current resource status.  This means that the Security Group cannot currently be changed by puppet once set.  This decision is inline with other aspects of `azure_vm` that are only used at creation time.
> (MODULES-5005) Support network security group name 5/6

- Gemfile
- README.md
- lib/puppet/provider/azure_resource_group/arm.rb
- lib/puppet/provider/azure_storage_account/arm.rb
- lib/puppet/provider/azure_vm/azure_arm.rb
- lib/puppet/type/azure_resource_group.rb
- lib/puppet/type/azure_storage_account.rb
- lib/puppet/type/azure_vm.rb
- lib/puppet_x/puppetlabs/azure/property/boolean.rb
- lib/puppet_x/puppetlabs/azure/provider_arm.rb
- spec/unit/type/azure_resource_group_spec.rb
- spec/unit/type/azure_storage_account_spec.rb
- spec/unit/type/azure_vm_spec.rb
Modify azure_vm, azure_storage_account and azure_resource_group to support a new parameter `tags` which accepts a hash of tags to associate with the resource.
Addresses https://tickets.puppetlabs.com/browse/MODULES-5002
> (MODULES-5002) support for azure resource tagging 6/6

- Gemfile
- README.md
- lib/puppet/provider/azure_resource_group/arm.rb
- lib/puppet/provider/azure_storage_account/arm.rb
- lib/puppet/provider/azure_vm/azure_arm.rb
- lib/puppet/type/azure_resource_group.rb
- lib/puppet/type/azure_storage_account.rb
- lib/puppet/type/azure_vm.rb
- lib/puppet_x/puppetlabs/azure/config.rb
- lib/puppet_x/puppetlabs/azure/property/boolean.rb
- lib/puppet_x/puppetlabs/azure/provider_arm.rb
- spec/unit/type/azure_resource_group_spec.rb
- spec/unit/type/azure_storage_account_spec.rb
- spec/unit/type/azure_vm_spec.rb
Check that the `azure` and `azure_hocon` features (gems) are loaded onto the system before trying to require any files from the azure gem.  This prevents the provider failing abruptly if libraries are missing
> (MODULES-5048) check before loading azure libs 7/6

- Gemfile
- README.md
- lib/puppet/provider/azure_resource_group/arm.rb
- lib/puppet/provider/azure_storage_account/arm.rb
- lib/puppet/provider/azure_vm/azure_arm.rb
- lib/puppet/type/azure_resource_group.rb
- lib/puppet/type/azure_storage_account.rb
- lib/puppet/type/azure_vm.rb
- lib/puppet_x/puppetlabs/azure/config.rb
- lib/puppet_x/puppetlabs/azure/property/boolean.rb
- lib/puppet_x/puppetlabs/azure/provider_arm.rb
- spec/unit/type/azure_resource_group_spec.rb
- spec/unit/type/azure_storage_account_spec.rb
- spec/unit/type/azure_vm_spec.rb
Parse network names with slashes to allow looking up networking objects from other resource groups.  This allows us to _plug in_ to virtual networks, subnets and network security groups created in other resource groups
> (MODULES-5059) cross-resourcegroup networking 9/6

- Gemfile
- README.md
- lib/puppet/provider/azure_resource_group/arm.rb
- lib/puppet/provider/azure_storage_account/arm.rb
- lib/puppet/provider/azure_vm/azure_arm.rb
- lib/puppet/type/azure_resource_group.rb
- lib/puppet/type/azure_storage_account.rb
- lib/puppet/type/azure_vm.rb
- lib/puppet_x/puppetlabs/azure/config.rb
- lib/puppet_x/puppetlabs/azure/property/boolean.rb
- lib/puppet_x/puppetlabs/azure/provider_arm.rb
- rakelib/acceptance.rake
- spec/acceptance/arm_vm_cross_rg_spec.rb
- spec/acceptance/arm_vm_datadisks_spec.rb
- spec/acceptance/arm_vm_managed_disk_spec.rb
- spec/acceptance/arm_vm_no_publicip_spec.rb
- spec/acceptance/arm_vm_plan_spec.rb
- spec/acceptance/arm_vm_security_group_spec.rb
- spec/acceptance/multi_role_service_spec.rb
- spec/acceptance/nodesets/vagrant/centos7.yml
- spec/acceptance/resource_group_spec.rb
- spec/acceptance/storage_account_spec.rb
- spec/acceptance/windows_machine_spec.rb
- spec/spec_helper_acceptance.rb
- spec/unit/type/azure_resource_group_spec.rb
- spec/unit/type/azure_storage_account_spec.rb
- spec/unit/type/azure_vm_spec.rb
* Fix tests to work with newer azure libraries
* Fix invalid test settings due to changes in azure (invalid image IDs, etc)
* Fix rubocop errors/warnings
* Fix regression:  List paging for resource groups/VMs was removed - reinstated
* Fix bug:  Missing variable error in some situations
* Added tests for functionality added in previous patches
Note - I seemed to need a different vagrant image to get this to work nicely - one with "Development Tools" already installed.
> (MAINT) Fix test infrastructure for updated API and patches 10/6

- README.md
* Current instructions link to 2.0 CLI which does not apply to the
current instructions.
* Mention that this uses 1.0 CLI and update link to it (old one
redirects to 2.0 CLI)
* Note that 2.0 CLI exists but is not used by these instructions.
* Fixed index reference.
> (MODULES-5379) Update puppetlabs-azure Instructions

- README.md
-   Fix TOC list item alignment.
-   Add Development section to TOC.
-   Remove extraneous leading spaces from a list and some paragraphs.
-   Add line breaks after headings.
-   Adjust heading levels of Usage subsections.
-   Adjust hash rocket alignment in Puppet code.
-   Update customer support link.
> (docs) Tweak or fix Markdown formatting in README

- CHANGELOG.md
- Gemfile
- README.md
- lib/puppet/provider/azure_storage_account/arm.rb
- lib/puppet/type/azure_storage_account.rb
- lib/puppet_x/puppetlabs/azure/provider_arm.rb
- spec/acceptance/storage_account_spec.rb
- spec/spec_helper_acceptance.rb
- spec/unit/type/azure_storage_account_spec.rb
Catches invalid storage account names
Increases the number of problems caught
Provides a useful error message if operation fails
Deprecates account_type in favor of sku_name
> Add sku, tier, and https-only storage account params

- lib/puppet_x/puppetlabs/azure/provider_arm.rb
This puts the simple, clear errors I'd used on the other PRs on all try/rescue operations.
> Provide simple, clear errors when they are available.

- lib/puppet/provider/azure_resource_template/arm.rb
- In certain situations when the RG is empty the params returns empty and the module fails
- Fix when the return value is an empty hash or nil
> Fix params when return value is nil

- lib/puppet/provider/azure_vm/azure_arm.rb
- lib/puppet/type/azure_vm.rb
- lib/puppet_x/puppetlabs/azure/provider_arm.rb
- lib/puppet_x/puppetlabs/azure/provider_base.rb
- spec/unit/provider/azure_vm/azure_arm_spec.rb
The module (class azure_vm) as is was had no support for a deallocated ensure state.
As Azure continues to bill for vms in a stopped state I added the deallocated state.
All defaults remain the same, but manifest requesting and ensure state of deallocated will now work
test harness updated accordingly.
> Added deallocated state to help with cost control
