puppetlabs/puppetlabs-azure

README.md
- Add notes for anything Windows specific not addressed in README:
- How to install gems on Windows
- Gotchas with HOCON config files
- Appropriate info on how to SET environment variables in cmd.exe
- Also add clarification about how custom_data is handled on
Windows hosts
=> (CLOUD-486) Update documentation for Windows

lib/puppet_x/puppetlabs/azure/provider_arm.rb
The azure api gems raise MSAZURE exceptions when there is
a failure. It is important to report the message within that
exception, so that a user knows cause for the failure.
I've tested azure_vm_classic with the same failure causes as ones I've found or had been reported for the azure_vm resource, and it doesn't appear that the azure_sdk gem has the same issue. Errors were reported correctly.
/cc @DavidS
=> (CLOUD-497) Report embedded error messages

README.md
See also https://github.com/Azure/azure-sdk-for-ruby/pull/320
=> (FM-4815) Document the fact that custom_data only works for Linux hosts

lib/puppet/provider/azure_resource_group/arm.rb, lib/puppet/type/azure_resource_group.rb, lib/puppet_x/puppetlabs/azure/provider_arm.rb, lib/puppet_x/puppetlabs/azure/provider_base.rb, spec/acceptance/fixtures/azure_resource_group.pp.tmpl, spec/acceptance/resource_group_spec.rb, spec/support/context/puppet_resource_run.rb, spec/unit/type/azure_resource_group_spec.rb
Testing seems to be impacted by https://tickets.puppetlabs.com/browse/BKR-822 and can be mitigated with https://github.com/puppetlabs/beaker-testmode_switcher/pull/2 though an upstream fix is preferential.
=> (FM-5229) Add azure_resource_group resource

lib/puppet/provider/azure_resource_group/arm.rb, lib/puppet/provider/azure_storage_account/arm.rb, lib/puppet/type/azure_resource_group.rb, lib/puppet/type/azure_storage_account.rb, lib/puppet_x/puppetlabs/azure/provider_arm.rb, lib/puppet_x/puppetlabs/azure/provider_base.rb, spec/acceptance/fixtures/azure_resource_group.pp.tmpl, spec/acceptance/fixtures/azure_storage_account.pp.tmpl, spec/acceptance/resource_group_spec.rb, spec/acceptance/storage_account_spec.rb, spec/support/context/puppet_resource_run.rb, spec/unit/type/azure_resource_group_spec.rb, spec/unit/type/azure_storage_account_spec.rb
=> Add storage account

lib/puppet/type/azure_vm.rb
This matches other types like https://github.com/puppetlabs/puppetlabs-azure/blob/master/lib/puppet/type/azure_storage_account.rb#L19
=> Don't fail on ensure => absent

README.md
Adding required documentation for new Azure types: VM Extensions, Storage Accounts, and Resource Groups. These types are basic Azure resources required for most deployments. Provided working examples for each type as well as reference parameters at the bottom of the document.
=> (Docs) Updating Documentation for New Azure Types

CHANGELOG.md
More bugfixes I found when reading the diff.
=> Add some more 1.0.3 changelogs

CHANGELOG.md, examples/hanselmanfarm/init_simple.pp, examples/hanselmanfarm/init_ssh.pp, lib/puppet/type/azure_vm.rb, lib/puppet_x/puppetlabs/azure/provider_arm.rb, metadata.json
The release branch contains 6 commits, three of which are revert commits of previous master features that we did not want to release in the bugfix 1.0.3. This is a mergeback of the additional three commits made as part of the 1.0.3 release.
=> 1.0.3 Mergeback

.travis.yml, README.md, lib/puppet/provider/azure_vm/azure_arm.rb, lib/puppet/type/azure_vm.rb, lib/puppet_x/puppetlabs/azure/provider_arm.rb, spec/acceptance/arm_vm_datadisks_spec.rb, spec/acceptance/fixtures/azure_data_disks.pp.tmpl, spec/unit/type/azure_vm_spec.rb
Superseding #114 with some fixes for travis.
=> Minor fixes

lib/puppet_x/puppetlabs/azure/provider.rb, lib/puppet_x/puppetlabs/azure/provider_base.rb
Move encode and chomp the newline
=> Bugfix custom_data

README.md
Prior to this PR, it looked like it had a hard requirement on PE.
=> Clarified language a little bit

README.md
I changed the install section a fair bit, making it into an ordered list. Please look at that section carefully and let me know if I changed meaning or got something wrong.
=> PLEASE REVIEW: Edit on azure module readme

locales/config.yaml, locales/puppetlabs-azure.pot
As Azure is not part of modulesync, the locales directory and the config.yaml file needs to be created.
=> Creating locales folder and config.yaml

lib/puppet_x/puppetlabs/azure/provider_arm.rb
Fixed:
* calls to .get() on azure clients needs to be in a begin rescue block, as if it fails to find the target, it throws an exception and breaks the code.
* build_params had to be moved to before the storage account, due to dependencies.
*  def create_virtual_network(args)
-          Puppet.debug("Creating vnet '#{virtual_network.name}'")  <= virtual_network doesnt exist? and caused an exception in the success path.
=> (CLOUD-1005) create vm with ARM fails

README.md
This ticket is to allow Garret to reivew the Readme ahead of the release
=> (CLOUD-1221) Review the README for release

README.md
Formatted and edited for translation.
=> prep for translation

README.md
Exising puppet azure module alreadys supports SSD storage (feature request unnecessary) so I just make the documentation around it a bit clearer.
=> (MODULES-5007) Document support for SSD storage - 1/6

Gemfile, README.md, lib/puppet/provider/azure_resource_group/arm.rb, lib/puppet/provider/azure_storage_account/arm.rb, lib/puppet/provider/azure_vm/azure_arm.rb, lib/puppet/type/azure_resource_group.rb, lib/puppet/type/azure_storage_account.rb, lib/puppet/type/azure_vm.rb, lib/puppet_x/puppetlabs/azure/config.rb, lib/puppet_x/puppetlabs/azure/property/boolean.rb, lib/puppet_x/puppetlabs/azure/provider_arm.rb, spec/unit/type/azure_resource_group_spec.rb, spec/unit/type/azure_storage_account_spec.rb, spec/unit/type/azure_vm_spec.rb
Protect against module failure from absent data in some environments by checking required objects exist before calling their methods
=> (MODULES-5057) Check object present before method calls 8/6

README.md
=> (CLOUD-1441) Readme changes

Gemfile, lib/puppet_x/puppetlabs/azure/provider_arm.rb, rakelib/acceptance.rake, spec/acceptance/arm_vm_spec.rb, spec/acceptance/multi_role_service_spec.rb, spec/acceptance/windows_machine_spec.rb, spec/spec_helper_acceptance.rb, spec/support/context/destroy_leftover_resources.rb, spec/support/context/with_known_names.rb
Big thanks to Geoff Williams.
Lots of changes to the acceptance tests to get them going again.
=> (MODULES-5964) 1.2 release of new content.

lib/puppet/provider/azure_subnet/arm.rb, lib/puppet/type/azure_subnet.rb, lib/puppet_x/puppetlabs/azure/provider_arm.rb, spec/acceptance/fixtures/azure_subnet.pp.tmpl, spec/acceptance/subnet_spec.rb, spec/unit/type/azure_subnet_spec.rb
=> New type azure_subnet builds on azure_vnet

.travis.yml
This avoids bumping into an issue with bundler.
=> (MODULES-6339) - Removing bundler update
